"""Tree-structured prior: targets generated by ensembles of oblivious decision trees.

Why this prior exists, and why it is not redundant with `scm.py`
----------------------------------------------------------------

MITRA (arXiv:2510.21204) proposes three criteria for selecting a prior — **performance**,
**diversity** and **distinctiveness** — and selects tree-based priors on the third alone:
models pretrained on structural-causal-model priors "do not always generalize well to all
types of data generated from TBPs". TabICL and TabForestPFN reach the same conclusion
independently. `docs/paper/RELATED_WORK.md` records the argument in full.

This project had no tree prior at all. `prior/scm.py` composes smooth-ish activations over a
random graph, which generates curved boundaries; a tree generates **axis-aligned piecewise
constant** structure, and no amount of `tanh` composition produces that shape efficiently.
Real tabular data is full of it — thresholds, brackets, policy cutoffs — and every baseline
this project loses to on TabArena is a tree ensemble.

**The distinctiveness claim is testable and must be tested, not assumed** (task 48.14): a
model trained on the SCM prior alone should do measurably *worse* on tree-generated tasks than
one trained with this prior mixed in. If it does not, this prior is adding step count rather
than signal, which is the most likely explanation of §93's 5x-volume null.

Why oblivious trees
-------------------

Each tree is **oblivious** (symmetric): the same split criterion applies to every node at a
given depth, so a depth-`d` tree is `d` thresholds rather than `2^d - 1`. Reimplemented from
the mechanism described in TabICLv2's Appendix E.8 (arXiv:2602.11139) — no code or weights
from that project enter this repository, per `CLAUDE.md`'s boundary.

Three properties make this the right choice here:

- **Evaluation is vectorised.** A depth-`d` oblivious tree assigns every row a leaf index by
  `d` independent comparisons combined as bits, so a whole forest evaluates without recursion
  or per-node bookkeeping. A prior runs in the training loop; a slow prior is a smaller model.
- **Split dimensions follow feature importance.** Choosing the split dimension with
  probability proportional to each column's standard deviation means a feature the upstream
  graph made variable is a feature the tree is likely to split on — so "important" features
  are consistently important, as in real data, rather than the label depending on an
  arbitrary column.
- **Ensembling smooths without removing the corners.** Averaging many shallow trees yields a
  target with genuine axis-aligned discontinuities but enough resolution to be learnable,
  which is exactly the structure a gradient-boosted baseline finds easy and an in-context
  model trained only on smooth priors may not.
"""

from __future__ import annotations

import numpy as np

from fintfm.prior.base import Task

#: Ceiling on trees per ensemble. Drawn log-uniformly, so most draws are far below this: a
#: forest of one is a step function and a forest of many is nearly smooth, and the prior needs
#: to span that range rather than sit at either end (`CLAUDE.md`, "a prior must span
#: difficulty").
MAX_TREES = 128

#: Ceiling on tree depth. Depth is the number of thresholds, so this is already deep for an
#: oblivious tree — 2^7 = 128 leaves.
MAX_DEPTH = 7


def _oblivious_forest(
    rng: np.random.Generator, X: np.ndarray, n_trees: int, depth: int
) -> np.ndarray:
    """Evaluate a random oblivious-tree ensemble on ``X``.

    Args:
        rng: NumPy random generator.
        X: ``(n_rows, n_features)`` inputs. Must be finite.
        n_trees: Number of trees to average.
        depth: Thresholds per tree.

    Returns:
        ``(n_rows,)`` averaged leaf values.
    """
    n_rows, n_features = X.shape
    # Split dimension sampled proportional to column spread, so the tree splits on features
    # that actually vary. A near-constant column is a useless split and would waste depth.
    spread = X.std(axis=0)
    total = spread.sum()
    p = spread / total if total > 0 else np.full(n_features, 1.0 / n_features)
    out = np.zeros(n_rows)
    for _ in range(n_trees):
        dims = rng.choice(n_features, size=depth, replace=True, p=p)
        # Thresholds are drawn from the arriving data rather than from a fixed grid, so a
        # split always separates some rows -- a threshold outside a column's range produces a
        # tree with an unreachable half and silently reduces the effective depth.
        thresholds = X[rng.integers(0, n_rows, size=depth), dims]
        # Leaf index as bits: each level contributes one comparison, combined by shifting.
        leaf = np.zeros(n_rows, dtype=np.int64)
        for level in range(depth):
            leaf = (leaf << 1) | (X[:, dims[level]] > thresholds[level])
        out += rng.normal(0.0, 1.0, size=1 << depth)[leaf]
    return out / n_trees


def sample_tree_task(
    rng: np.random.Generator,
    n_rows: int,
    max_features: int = 24,
    min_features: int = 2,
    max_classes: int = 10,
    _latent_out: list[np.ndarray] | None = None,
) -> Task:
    """Sample one classification task whose target is an oblivious-tree ensemble of the features.

    Unlike :func:`fintfm.prior.scm.sample_scm_task`, the features here are sampled first and
    the target is a function *of them*, rather than both being read off a shared latent graph.
    That is deliberate: the point of this prior is the **shape of the decision boundary**, and
    routing it through a latent graph would blur the axis-aligned structure it exists to teach.

    Args:
        rng: NumPy random generator.
        n_rows: Number of rows.
        max_features: Upper bound on the number of features.
        min_features: Lower bound on the number of features.
        max_classes: Upper bound on the number of classes (>= 2).
        _latent_out: Internal. When a list is passed, the continuous pre-threshold target is
            appended to it, matching `scm.py`'s hook so a regression variant can reuse this
            exact generative process.

    Returns:
        A :class:`fintfm.prior.base.Task` with ``source="tree"``.
    """
    n_features = int(rng.integers(min_features, max_features + 1))
    # Correlated features, not independent Gaussians: real tabular columns are correlated, and
    # an axis-aligned boundary over independent features is a much easier problem than over
    # correlated ones.
    n_latent = int(rng.integers(2, max(3, n_features + 1)))
    z = rng.normal(size=(n_rows, n_latent))
    loading = rng.normal(size=(n_latent, n_features)) / np.sqrt(n_latent)
    X = (z @ loading + rng.normal(0, rng.uniform(0.1, 0.8), size=(n_rows, n_features))).astype(
        np.float64
    )
    X *= np.exp(rng.normal(0, 1.0, size=n_features))  # heterogeneous scales, as in real tables

    n_trees = int(np.exp(rng.uniform(0.0, np.log(MAX_TREES))))
    depth = int(rng.integers(1, MAX_DEPTH + 1))
    t = _oblivious_forest(rng, X, n_trees, depth)
    t = t + rng.normal(0, rng.uniform(0.0, 1.5) * (t.std() + 1e-9), size=n_rows)
    if _latent_out is not None:
        _latent_out.append(t.copy())

    n_classes = int(rng.integers(2, max_classes + 1))
    if rng.random() < 0.5:
        edges = np.quantile(t, np.linspace(0, 1, n_classes + 1)[1:-1])
    else:
        edges = np.sort(rng.uniform(t.min(), t.max(), size=n_classes - 1))
    y = np.searchsorted(edges, t).astype(np.int64)
    present = np.unique(y)
    if len(present) < 2:
        y[rng.choice(n_rows, size=max(1, n_rows // 20), replace=False)] = (y[0] + 1) % n_classes
        present = np.unique(y)
    remap = {c: i for i, c in enumerate(present)}
    y = np.vectorize(remap.get)(y).astype(np.int64)

    is_cat = rng.random(n_features) < rng.uniform(0.0, 0.4)
    for j in np.flatnonzero(is_cat):
        k = int(rng.integers(2, 8))
        X[:, j] = np.searchsorted(
            np.quantile(X[:, j], np.linspace(0, 1, k + 1)[1:-1]), X[:, j]
        )
    if rng.random() < 0.5:
        X[rng.random(X.shape) < rng.uniform(0, 0.2)] = np.nan
    return Task(
        X=X.astype(np.float32), y=y, n_classes=len(present), is_categorical=is_cat, source="tree"
    )
