"""Kaggle kernel: FinTFM-R decisive arm `ppdai`, seed 0 (generated by make_real_arm_kernel.py).

From-scratch training at the A6 recipe (6,000 steps, `max_classes 10`, seed 0) with
30% of tasks drawn from the real `ppdai` panel. Its control is the no-change
`max_classes 10` model at the same seed (task_158_matched_control -> v4-cellattn-labels-mc10.pt); nothing else differs.
Pinned to commit d03af3d.
"""

import subprocess
import sys


def run(cmd):
    print("+ " + " ".join(cmd), flush=True)
    subprocess.run(cmd, check=True)


def main():
    run([sys.executable, "-m", "pip", "install", "--quiet",
         "fintfm[real] @ git+https://github.com/kabartay/fintfm.git@d03af3d"])
    import torch
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"torch {torch.__version__}, device {device}", flush=True)
    run([sys.executable, "-u", "-m", "fintfm.modeling.train",
         "--steps", "6000", "--batch-size", "8", "--n-rows-choices", "256,512,1024",
         "--d-cell", "48", "--d-model", "128", "--n-layers", "4", "--n-col-layers", "2",
         "--n-cell-blocks", "1", "--cell-labels", "--column-id-dim", "16",
         "--feature-chunk", "8", "--max-features", "136", "--max-classes", "10",
         "--p-financial", "1.0", "--seed", "0", "--device", device,
         "--checkpoint-every", "500",
         "--real-panels", "/kaggle/input/fintfm-r-panels/ppdai/panel.parquet=0.3",
         "--out", "/kaggle/working/fintfm-r-ppdai-s0.pt"])
    print("done")


if __name__ == "__main__":
    main()
