"""Kaggle kernel: FinTFM-R decisive arm `ppdai`, seed 0 (generated by make_real_arm_kernel.py).

From-scratch training at the A6 recipe (6,000 steps, `max_classes 10`, seed 0) with
30% of tasks drawn from the real `ppdai` panel. Its control is the no-change
`max_classes 10` model at the same seed (task_158_matched_control -> v4-cellattn-labels-mc10.pt); nothing else differs.
Pinned to commit d03af3d.
"""

import subprocess
import sys
from pathlib import Path


def run(cmd):
    print("+ " + " ".join(cmd), flush=True)
    subprocess.run(cmd, check=True)


def find_panel():
    # Kaggle has mounted datasets at more than one depth under /kaggle/input; search rather than
    # trust one layout, and require exactly one match so the wrong source cannot be picked up.
    hits = sorted(p for p in Path("/kaggle/input").rglob("ppdai/panel.parquet")
                  if "fintfm-r-panels" in str(p))
    if len(hits) != 1:
        sys.exit(f"expected one fintfm-r-panels/ppdai/panel.parquet under /kaggle/input, found {hits}")
    print(f"panel: {hits[0]}", flush=True)
    return hits[0]


def main():
    panel = find_panel()
    run([sys.executable, "-m", "pip", "install", "--quiet",
         "fintfm[real] @ git+https://github.com/kabartay/fintfm.git@d03af3d"])
    import torch
    print(f"torch {torch.__version__}, CUDA available: {torch.cuda.is_available()}", flush=True)
    if not torch.cuda.is_available():
        # An exhausted GPU quota runs the kernel on CPU, where 6,000 steps cannot finish in a
        # session; stopping here costs nothing.
        sys.exit("no GPU in this session (quota exhausted?) -- refusing a CPU run")
    device = "cuda"
    run([sys.executable, "-u", "-m", "fintfm.modeling.train",
         "--steps", "6000", "--batch-size", "8", "--n-rows-choices", "256,512,1024",
         "--d-cell", "48", "--d-model", "128", "--n-layers", "4", "--n-col-layers", "2",
         "--n-cell-blocks", "1", "--cell-labels", "--column-id-dim", "16",
         "--feature-chunk", "8", "--max-features", "136", "--max-classes", "10",
         "--p-financial", "1.0", "--seed", "0", "--device", device,
         "--checkpoint-every", "500",
         "--real-panels", f"{panel}=0.3",
         "--out", "/kaggle/working/fintfm-r-ppdai-s0.pt"])
    print("done")


if __name__ == "__main__":
    main()
