"""Generate Kaggle kernels for FinTFM-R decisive runs (tasks A6/C5), one per real-data arm.

Each kernel trains from scratch at the exact reference recipe of the A6 control
(`runs/v4-cellattn-labels.pt`: §91/§127 architecture, 6,000 steps, seed 0, `--cell-labels`), adding
one `--real-panels` entry. That makes the existing control the matched comparison -- no control
needs retraining -- and the only axis that differs is the real source. Checkpoints come back with
`kaggle kernels output`; scoring on V4FinBench happens locally, as for every earlier Kaggle run.

Panels reach the kernel as a **private** Kaggle dataset (`--dataset`, staged by
`stage_real_panels.sh`), mounted at `/kaggle/input/<slug>/<source>/panel.parquet`. Freddie Mac is
never staged there: its free-tier terms cover internal use (§153), and copying it to a third-party
host is not something to decide in a script.

Usage:
    uv run python scripts/kaggle/make_real_arm_kernel.py --commit 0dc530e sba ulb_fraud
    kaggle kernels push -p scripts/kaggle/fintfm_r_sba
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent

#: Sources that may be staged to a private Kaggle dataset (licences in data_candidates.csv).
STAGEABLE = ("edgar", "sba", "ulb_fraud", "bondora", "ppdai", "lendingclub")

TEMPLATE = '''"""Kaggle kernel: FinTFM-R decisive arm `{arm}` (generated by make_real_arm_kernel.py).

From-scratch training at the A6 control's exact recipe (6,000 steps, seed 0) with
{share:.0%} of tasks drawn from the real `{arm}` panel. The control is the existing
`v4-cellattn-labels.pt`; nothing else differs. Pinned to commit {commit}.
"""

import subprocess
import sys


def run(cmd):
    print("+ " + " ".join(cmd), flush=True)
    subprocess.run(cmd, check=True)


def main():
    run([sys.executable, "-m", "pip", "install", "--quiet",
         "fintfm[real] @ git+https://github.com/kabartay/fintfm.git@{commit}"])
    import torch
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"torch {{torch.__version__}}, device {{device}}", flush=True)
    run([sys.executable, "-u", "-m", "fintfm.modeling.train",
         "--steps", "6000", "--batch-size", "8", "--n-rows-choices", "256,512,1024",
         "--d-cell", "48", "--d-model", "128", "--n-layers", "4", "--n-col-layers", "2",
         "--n-cell-blocks", "1", "--cell-labels", "--column-id-dim", "16",
         "--feature-chunk", "8", "--max-features", "136", "--max-classes", "2",
         "--p-financial", "1.0", "--seed", "0", "--device", device,
         "--checkpoint-every", "500",
         "--real-panels", "/kaggle/input/{dataset}/{arm}/panel.parquet={share}",
         "--out", "/kaggle/working/fintfm-r-{arm}.pt"])
    print("done")


if __name__ == "__main__":
    main()
'''


def main() -> None:
    """Write one kernel directory per requested arm."""
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("arms", nargs="+", choices=STAGEABLE)
    p.add_argument("--commit", required=True, help="fintfm commit to pin the kernel to")
    p.add_argument("--share", type=float, default=0.3, help="fraction of tasks from the source")
    p.add_argument("--dataset", default="fintfm-r-panels", help="private Kaggle dataset slug")
    p.add_argument("--user", default="muhakabartay")
    args = p.parse_args()
    for arm in args.arms:
        slug = f"fintfm-r-{arm.replace('_', '-')}"
        out = HERE / f"fintfm_r_{arm}"
        out.mkdir(exist_ok=True)
        code = out / f"fintfm_r_{arm}.py"
        code.write_text(TEMPLATE.format(
            arm=arm, share=args.share, commit=args.commit, dataset=args.dataset
        ))
        # id must equal the slug Kaggle derives from the title, or push fails with 409/400 --
        # the mismatch that cost several launches earlier in this project.
        meta = {
            "id": f"{args.user}/{slug}", "title": slug, "code_file": code.name,
            "language": "python", "kernel_type": "script", "is_private": "true",
            "enable_gpu": "true", "enable_tpu": "false", "enable_internet": "true",
            "dataset_sources": [f"{args.user}/{args.dataset}"],
            "competition_sources": [], "kernel_sources": [], "model_sources": [],
        }
        (out / "kernel-metadata.json").write_text(json.dumps(meta, indent=2) + "\n")
        print(f"wrote {out.relative_to(HERE.parents[1])}")


if __name__ == "__main__":
    main()
