"""Generate Kaggle kernels for FinTFM-R decisive runs (tasks A6/C5), one per real-data arm.

Each kernel trains from scratch at the A6 reference recipe (§91/§127 architecture, 6,000 steps,
`--cell-labels`) at `--max-classes 10`, adding one `--real-panels` entry, at one seed per kernel.

**Why `max_classes 10`, not the A6 control's 2 (§158).** A no-change replicate differs from the
control by −0.0073 mean AP with one fold at p < 0.001, so a single-seed arm cannot resolve an
effect of the pilot's size (§157: SBA +0.0073 over five folds). At head size 10 both controls
already exist or are queued for another reason: seed 0 is `task_158_matched_control`, seed 1 is
the scored replicate `runs/cellattn-s1-kaggle/v4-cellattn-labels-s1.pt`. Each arm runs at seeds
0 and 1 and is compared seed-for-seed; within a pair, only the real source differs. Checkpoints
come back with `kaggle kernels output`; scoring on V4FinBench happens locally, as for every
earlier Kaggle run.

Panels reach the kernel as a **private** Kaggle dataset (`--dataset`, staged by
`stage_real_panels.sh`), mounted at `/kaggle/input/<slug>/<source>/panel.parquet`. Freddie Mac is
never staged there: its free-tier terms cover internal use (§153), and copying it to a third-party
host is not something to decide in a script.

Usage:
    uv run python scripts/kaggle/make_real_arm_kernel.py --commit <sha> --seeds 0,1 sba
    kaggle kernels push -p scripts/kaggle/fintfm_r_sba_s0
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent

#: Sources that may be staged to a private Kaggle dataset (licences in data_candidates.csv).
STAGEABLE = ("edgar", "sba", "ulb_fraud", "bondora", "ppdai", "lendingclub")

#: The `max_classes 10` no-change model each seed is compared against (§158).
CONTROLS = {
    0: "task_158_matched_control -> v4-cellattn-labels-mc10.pt",
    1: "runs/cellattn-s1-kaggle/v4-cellattn-labels-s1.pt",
}

TEMPLATE = '''"""Kaggle kernel: FinTFM-R decisive arm `{arm}`, seed {seed} (generated by make_real_arm_kernel.py).

From-scratch training at the A6 recipe (6,000 steps, `max_classes 10`, seed {seed}) with
{share:.0%} of tasks drawn from the real `{arm}` panel. Its control is the no-change
`max_classes 10` model at the same seed ({control}); nothing else differs.
Pinned to commit {commit}.
"""

import subprocess
import sys


def run(cmd):
    print("+ " + " ".join(cmd), flush=True)
    subprocess.run(cmd, check=True)


def main():
    run([sys.executable, "-m", "pip", "install", "--quiet",
         "fintfm[real] @ git+https://github.com/kabartay/fintfm.git@{commit}"])
    import torch
    print(f"torch {{torch.__version__}}, CUDA available: {{torch.cuda.is_available()}}", flush=True)
    if not torch.cuda.is_available():
        # An exhausted GPU quota runs the kernel on CPU, where 6,000 steps cannot finish in a
        # session; stopping here costs nothing.
        sys.exit("no GPU in this session (quota exhausted?) -- refusing a CPU run")
    device = "cuda"
    run([sys.executable, "-u", "-m", "fintfm.modeling.train",
         "--steps", "6000", "--batch-size", "8", "--n-rows-choices", "256,512,1024",
         "--d-cell", "48", "--d-model", "128", "--n-layers", "4", "--n-col-layers", "2",
         "--n-cell-blocks", "1", "--cell-labels", "--column-id-dim", "16",
         "--feature-chunk", "8", "--max-features", "136", "--max-classes", "10",
         "--p-financial", "1.0", "--seed", "{seed}", "--device", device,
         "--checkpoint-every", "500",
         "--real-panels", "/kaggle/input/{dataset}/{arm}/panel.parquet={share}",
         "--out", "/kaggle/working/fintfm-r-{arm}-s{seed}.pt"])
    print("done")


if __name__ == "__main__":
    main()
'''


def main() -> None:
    """Write one kernel directory per requested arm."""
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("arms", nargs="+", choices=STAGEABLE)
    p.add_argument("--commit", required=True, help="fintfm commit to pin the kernel to")
    p.add_argument("--share", type=float, default=0.3, help="fraction of tasks from the source")
    p.add_argument("--dataset", default="fintfm-r-panels", help="private Kaggle dataset slug")
    p.add_argument("--user", default="muhakabartay")
    p.add_argument("--seeds", default="0,1",
                   help=f"comma-separated; each needs a matched control, one of {sorted(CONTROLS)}")
    args = p.parse_args()
    seeds = [int(s) for s in args.seeds.split(",")]
    if unmatched := [s for s in seeds if s not in CONTROLS]:
        raise SystemExit(f"no max_classes 10 control exists for seed(s) {unmatched}")
    for arm, seed in ((a, s) for a in args.arms for s in seeds):
        slug = f"fintfm-r-{arm.replace('_', '-')}-s{seed}"
        out = HERE / f"fintfm_r_{arm}_s{seed}"
        out.mkdir(exist_ok=True)
        code = out / f"fintfm_r_{arm}_s{seed}.py"
        code.write_text(TEMPLATE.format(
            arm=arm, seed=seed, control=CONTROLS[seed], share=args.share,
            commit=args.commit, dataset=args.dataset,
        ))
        # id must equal the slug Kaggle derives from the title, or push fails with 409/400 --
        # the mismatch that cost several launches earlier in this project.
        meta = {
            "id": f"{args.user}/{slug}", "title": slug, "code_file": code.name,
            "language": "python", "kernel_type": "script", "is_private": "true",
            "enable_gpu": "true", "enable_tpu": "false", "enable_internet": "true",
            "dataset_sources": [f"{args.user}/{args.dataset}"],
            "competition_sources": [], "kernel_sources": [], "model_sources": [],
        }
        (out / "kernel-metadata.json").write_text(json.dumps(meta, indent=2) + "\n")
        print(f"wrote {out.relative_to(HERE.parents[1])}")


if __name__ == "__main__":
    main()
