"""Kaggle kernel: FinTFM-R decisive arm `sba`, seed 1 (generated by make_real_arm_kernel.py).

From-scratch training at the A6 recipe (6,000 steps, `max_classes 10`, seed 1) with
30% of tasks drawn from the real `sba` panel. Its control is the no-change
`max_classes 10` model at the same seed (runs/cellattn-s1-kaggle/v4-cellattn-labels-s1.pt); nothing else differs.
Pinned to commit d03af3d.
"""

import subprocess
import sys


def run(cmd):
    print("+ " + " ".join(cmd), flush=True)
    subprocess.run(cmd, check=True)


def main():
    run([sys.executable, "-m", "pip", "install", "--quiet",
         "fintfm[real] @ git+https://github.com/kabartay/fintfm.git@d03af3d"])
    import torch
    print(f"torch {torch.__version__}, CUDA available: {torch.cuda.is_available()}", flush=True)
    if not torch.cuda.is_available():
        # An exhausted GPU quota runs the kernel on CPU, where 6,000 steps cannot finish in a
        # session; stopping here costs nothing.
        sys.exit("no GPU in this session (quota exhausted?) -- refusing a CPU run")
    device = "cuda"
    run([sys.executable, "-u", "-m", "fintfm.modeling.train",
         "--steps", "6000", "--batch-size", "8", "--n-rows-choices", "256,512,1024",
         "--d-cell", "48", "--d-model", "128", "--n-layers", "4", "--n-col-layers", "2",
         "--n-cell-blocks", "1", "--cell-labels", "--column-id-dim", "16",
         "--feature-chunk", "8", "--max-features", "136", "--max-classes", "10",
         "--p-financial", "1.0", "--seed", "1", "--device", device,
         "--checkpoint-every", "500",
         "--real-panels", "/kaggle/input/fintfm-r-panels/sba/panel.parquet=0.3",
         "--out", "/kaggle/working/fintfm-r-sba-s1.pt"])
    print("done")


if __name__ == "__main__":
    main()
